### ISSUE TITLE
I don't find Swing Explorer Working in Idea 2016.2?

### ISSUE THREAD

**Issue by narendranss** [wglanzer/swingexplorer-idea#1]
I don't find Swing Explorer Working in Idea 2016.2? Any Idea what may be wrong? I just installed it from plugin Repository, which had below note.

> The plug-in integrates SwingExplorer into IntelliJ IDEA. SwingExplorer is a tool for Java Swing application debugging. Usage instructions are available here
> The plug-in was contributed by Piotr Mlocek
> Change Notes
> Incorporates Swing Explorer ${build.version}
> Vendor
> Swing Explorer http://www.swingexplorer.com info@swingexplorer.com
> Plugin homepage
> http://swingexplorer.com

**Comment by wglanzer** [comment]
Hi,
I think you downloaded the wrong version of the plugin.
The plugin is named "SwingExplorer Integration v2", and I verified that it works (last week).
Maybe I should add this to my README.. Shame on me.. :smile: 
The actual version is: "2016.1-1.6.0-1.0.1"

**Comment by narendranss** [comment]
I did comment on the Plugin page - https://plugins.jetbrains.com/idea/plugin/8385-swingexplorer-integration-v2. Thank you. It did help a lot :)
