### ISSUE TITLE
The plugin doesn't working in Idea 2017.1.5

### ISSUE THREAD

**Issue by wwarlock** [wglanzer/swingexplorer-idea#2]
The plugin was installed earlier and verified as working.
After some time a few Idea versions was released and plugin moved between Idea instances without errors.
But the run button is gone to the gray colour.
Today I've tried to reenable the plugin in the next way:
1) `Ctrl + Shift + A`
2) SwingExplorer Integration v2 [Green ON]
3) Restart Idea.
The button from the toolbar has disappeared.

4) `Ctrl + Shift + A`
5) SwingExplorer Integration v2 [Gray OFF]
6) Restart Idea
No result, the plugin is staying in disabled state.

**Comment by wglanzer** [comment]
- Already fixed
