### ISSUE TITLE
I don't find Swing Explorer Working in Idea 2018.3

### ISSUE THREAD

**Issue by e10indika** [wglanzer/swingexplorer-idea#3]
I don't find Swing Explorer Working in Idea 2018.3? Any Idea what may be wrong? I just installed it from plugin Repository. 
I think I downloaded the correct version of the plugin.
The plugin is named "SwingExplorer Integration v2"

Actual version is : v182.4505.22-1.6.0.

**Comment by wglanzer** [comment]
Since this ticket is stale over one year now, I am going to close it.
