### ISSUE TITLE
Plugin does not work with >2021.2

### ISSUE THREAD

**Issue by Goddard** [wglanzer/swingexplorer-idea#6]
I'm kinda new to this tool and it would be really awesome if it had a very short explanation of how to use it.

**Comment by andez2000** [comment]
I second that.

Blue icon in IntelliJ.  Click to run the application - but then what?

It works on my colleagues IntelliJ Community 2020.2,3.

Not working for my Ultimate 2021.2.1 version.

**Comment by JavaMaxim** [comment]
Seems that it doesn't work with IntelliJ Community 2021.2.2

**Comment by mattventura** [comment]
Also seeing this. My program launches, Swing Explorer doesn't.

**Comment by wglanzer** [comment]
Hi there,

@Goddard : I added a small description to the README 👍 

@andez2000 , @JavaMaxim , @mattventura : Fixed it today - plugin update "1.7.0" for IJ >2021.2 is contributed. Should be publicly available within two days, after the review process of JetBrains finished.

**Comment by JavaMaxim** [comment]
Thanks!
